name: scaffold-dispatch
run-name: ${{ github.actor }}

on: 
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment, this will be used as workspace'
                required: true
                default: 'dev'
                type: choice
                options:
                    - dev
                    - staging
                    - prod
            action:
              description: "Chose between create or destroy the environment"
              required: true
              type: choice
              default: create
              options:
                - plan-only # Only for visual, if plan only and destroy are selected, then it will plan a destroy but not apply
                - create 
                - destroy
                    
env:
    # ROLE_TO_ASSUME: arn:aws:iam::760772947412:role/github-actions/gh-oidc
    AWS_REGION: us-east-1


permissions:
    id-token: write
    contents: read

jobs:
  scaffold:
    uses: ./.github/workflows/terraform.yml
    with:
      apply: ${{ inputs.action != 'plan-only' }}
      destroy: ${{ inputs.action == 'destroy' }}
      fmt-check: false
      workspace: ${{ inputs.environment  }}
      working-dir: infrastructure/scaffold
      role-to-assume: arn:aws:iam::760772947412:role/github-actions/gh-oidc
